name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - run: npm install -D vuepress

      - run: npm install -D @vuepress/plugin-back-to-top

      - run: npm run build

      - name: Vuepress-deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: pages
          PUBLISH_DIR: docs/.vuepress/dist/
