name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Github config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Vuepress-deploy
        uses: jenkey2011/vuepress-deploy@1.8.1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
